name: Deployment Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: '@mindfiredigital/pagebuilder'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: 'Install dependencies with pnpm'
        run: pnpm install # Install all dependencies using pnpm

      - name: 'Build application'
        run: pnpm turbo run build # Assuming there's a build script in each package

      - name: 'Restore changes in pnpm lock'
        run: |
          git restore pnpm-lock.yaml  # Restore any changes in lock files if needed

      - name: 'Set Git user name and email'
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

  create-github-release:
    name: Create GitHub release document and publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Semantic Release and npm release
        run: |
          pnpm install --frozen-lockfile
          pnpm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
